language: python
env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
python:
  - "2.6"
  - "2.7"
  - "pypy"
# command to install dependencies
install:
  - pip install .
  - pip install -r test-requirements.txt
  - if [ $DJANGO = "1.4" ] ; then pip install https://github.com/django/django/archive/stable/1.4.x.zip#egg=django; fi
  - if [ $DJANGO = "1.5" ] ; then pip install https://github.com/django/django/archive/stable/1.5.x.zip#egg=django; fi
  - if [ $DJANGO = "1.6" ] ; then pip install https://github.com/django/django/archive/stable/1.6.x.zip#egg=django; fi
  - if [ $DJANGO = "1.7" ] ; then pip install https://github.com/django/django/archive/stable/1.7.x.zip#egg=django; fi
# command to run tests
script: ./runtests.sh
